# Generated by Django 5.1.6 on 2025-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField()),
                ('tile_x', models.IntegerField()),
                ('tile_y', models.IntegerField()),
                ('tile_image', models.ImageField(upload_to='tiles/')),
            ],
            options={
                'unique_together': {('zoom', 'tile_x', 'tile_y')},
            },
        ),
    ]
